### PR TITLE
Fix proof verification for zero append bitmap

### LINKED ISSUE #99: zero byte at the beginning or the end of proof bitmap should be invalid
### Expected behavior
It should fail on smt verify if bitmap includes zero byte at the begging or the end, smt.verify should fail.

### Actual behavior
it fails on verify if zero byte is appended but not when prepended

### Steps to reproduce
Modify tests to prepend and append zero bytes to proof bitmap, and call `verify`

### Which version(s) does this affect? (Environment, OS, etc...)
0.3.4

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #99 

### How was it solved?

- Add check on `verify_query_keys`

### How was it tested?

- Added unit test to verify zero byte append and prepend bitmap proof

### CODE REVIEW

File: src/sparse_merkle_tree/smt.rs [hunk 1]
```diff
@@ -863,6 +863,9 @@ impl SparseMerkleTree {
             if utils::is_bytes_equal(key, query.key()) {
                 continue;
             }
+            if query.bitmap.len() > 0 && query.bitmap[0] == 0 {
```
Comment (hrmhatef) [inline src/sparse_merkle_tree/smt.rs:866]: We do not need to check `zero` value at the end of the `bitmap`, because the issue mentioned at the begging or the end.

**Review by hrmhatef — APPROVED** [review]

**Review by matjazv — APPROVED** [review]

File: src/sparse_merkle_tree/smt.rs (hunk 1 above)
Comment (shuse2) [reply src/sparse_merkle_tree/smt.rs:863]: it was actually valid to have ending `0` with the bitmap, but it should fail if we append `0` (which becomes invalid)

**Review by matjazv — APPROVED** [review]

File: src/sparse_merkle_tree/smt.rs [hunk 2]
```diff
@@ -1391,7 +1394,7 @@ impl SparseMerkleTree {
             if !sorted_queries.is_empty() && query.is_sibling_of(&sorted_queries[0]) {
                 let sibling = sorted_queries.pop_front().unwrap();
                 sibling_hash = Some(sibling.hash);
-            } else if !query.binary_bitmap[0] {
+            } else if !query.binary_bitmap[0] || sibling_hashes.len() == next_sibling_hash {
```
Comment (ricott1) [inline src/sparse_merkle_tree/smt.rs:1397]: In my understanding you are checking by hand if you have consumed all the sibling hashes, because you use the index `next_sibling_hash` rather than popping them (probably for efficiency reasons). 

I still don't understand why you need to do that. It looks to me that you would pass the check even if `query.binary_bitmap[0] == 1` if you have consumed all the sibling hashes. Doesn't this mean that one can append 1 bits to the end of the binary bitmap to enter this branch? I guess the resulting root would be wrong, but I don't see why we need this.

Comment (shuse2) [reply src/sparse_merkle_tree/smt.rs:1397]: I think it's true to say `query.binary_bitmap[0] == 1 if you have consumed all the sibling hash` it will use empty hash, but if it used up all the sibling hash and if `binary_bitmap[0] == 1`, it doesn't have sibling hash to use, so it should be simply error?

Comment (ricott1) [reply src/sparse_merkle_tree/smt.rs:1397]: yes, I think so

**Review by hrmhatef — APPROVED** [review]
LGTM.👍

**Review by matjazv — APPROVED** [review]

File: src/sparse_merkle_tree/smt.rs [hunk 3]
```diff
@@ -1394,6 +1397,11 @@ impl SparseMerkleTree {
             } else if !query.binary_bitmap[0] {
                 sibling_hash = Some(EMPTY_HASH.to_vec());
             } else if query.binary_bitmap[0] {
+                if sibling_hashes.len() == next_sibling_hash {
+                    return Err(SMTError::InvalidInput(String::from(
+                        "length of sibnling_hashes does not match with bitmap",
```
Comment (ricott1) [inline src/sparse_merkle_tree/smt.rs:1402]: You have a typo in the error string. Also, I'm not sure if the error is describing the issue very well, as the length of sibling hashes does not have to do with the bitmap only but also with the keys you are querying. I would write something like, "no more sibling hashes available" or something like that.

**Review by ricott1 — APPROVED** [review]
