### PR TITLE
Fix a variable name and its usage - Closes #66

### LINKED ISSUE #66: Invalid variable name and usage on smtdb
### Expected behavior
The behavior seems to be correct, but variable name and the usage seems to be invalid

### Actual behavior
https://github.com/LiskHQ/lisk-db/blob/main/src/state_db.rs#L583 this variable is `version` (ie: block height) as mentioned in the comment [here](https://github.com/LiskHQ/lisk-db/blob/main/src/state_db.rs#L574)

However, it is used as key_length [here](https://github.com/LiskHQ/lisk-db/blob/main/src/state_db.rs#L604)

### PR DESCRIPTION
**Pull request by hrmhatef**
### What was the problem?

This PR resolves #66 

### How was it solved?
 - Introduce a new base struct for `types::Options`
 - Introduce two new structs from `types::Options` for `DbOptions` and `CommitOptions`

### How was it tested?
 - All tests passed.

### CODE REVIEW

**Review by matjazv — APPROVED** [review]

File: src/state_db.rs [hunk 1]
```diff
@@ -854,7 +853,7 @@ impl StateDB {
     pub fn js_commit(mut ctx: FunctionContext) -> JsResult<JsUndefined> {
         let writer = ctx.argument::<state_writer::SendableStateWriter>(0)?;
 
-        let key_length = ctx.argument::<JsNumber>(1)?.value(&mut ctx).into();
+        let block_height = ctx.argument::<JsNumber>(1)?.value(&mut ctx).into();
```
Comment (shuse2) [inline src/state_db.rs:856]: here maybe we could name it `version` to be consistent with rest of the code

File: src/in_memory_db.rs [hunk 2]
```diff
@@ -93,7 +92,7 @@ impl JsNewWithBoxRef for Database {
         let db = U::new_db_with_context(
             &mut ctx,
             String::from(""),
-            DBOptions::new(),
+            DbOptions::new(false, KeyLength(0)),
```
[the remark this answers is not in the document]
Comment (hrmhatef) [reply src/in_memory_db.rs:95]: Yes you right, but this line used just for the Trait definition. We will not use any of these variables between lines `73-76` and `93-96`

File: src/state_db.rs (hunk 1 above)
Comment (hrmhatef) [reply src/state_db.rs]: Done.

File: src/state_db.rs [hunk 3]
```diff
@@ -162,12 +160,13 @@ impl StateDB {
...
         cb: Root<JsFunction>,
     ) -> Result<(), mpsc::SendError<options::DbMessage>> {
-        let key_length = self.options.key_length;
+        let key_length = self.options.key_length();
         self.common.send(move |conn, channel| {
             let result = StateDB::get_revert_result(conn, height, &state_root, key_length);
             if result.is_ok() {
                 let value = (**result.as_ref().unwrap().lock().unwrap()).clone();
-                let state_info = CurrentState::new(&value, height.sub(1).into());
+                let version = height.sub(1).into();
```
Comment (shuse2) [inline src/state_db.rs:168]: probably this input name also could be version?

File: src/in_memory_db.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (shuse2) [reply src/in_memory_db.rs:95]: If there is `DataBase` and `InMemoryDB` doesn't have `key_length` option, shouldnt we have separate struct for those?

[the remark this answers is not in the document]
Comment (hrmhatef) [reply src/in_memory_db.rs:95]: This a trait so each struct can implement it for own, if we want to separate them we should define a new trait for that. Also trait implementation means we have separate structure with same definition.

File: src/state_db.rs (hunk 3 above)
Comment (hrmhatef) [reply src/state_db.rs:168]: we use `height` for the `revert` function if the `revert` should take `version` so it would be correct to change it to `version` if not I think it is better to have height and convert it to version like current implementation.

Comment (shuse2) [reply src/state_db.rs:168]: i think to be slightly agnostic from the blockchain, we should change `block height` => `version`. So in the revert function also we can change it to version

File: src/in_memory_db.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (shuse2) [reply src/in_memory_db.rs:95]: Since it has completely different use-case, we could split the trait as well?
or maybe it's like 
```
struct DBOption {
  readonly bool,
}
struct StateDBOption {
  DBOption
  key_length; 
}
```
and commit option is completely different thing (which is already done)

File: src/state_db.rs (hunk 3 above)
Comment (hrmhatef) [reply src/state_db.rs:168]: Done.

File: src/in_memory_db.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (hrmhatef) [reply src/in_memory_db.rs]: Done.

**Review by shuse2 — APPROVED** [review]
