### PR TITLE
Fix prove/verify interface between JS and Rust - Closes #65

### LINKED ISSUE #65: StateDB proof/verify is not working
### Expected behavior
`StateDB.verify`  and `StateDB.proof` should be the same interface as `SparseMerkleTree.verify` and `SparseMerkleTree.proof`.

Unit test on JS should be added to ensure the interface is correct. Note that StateDB key is by default.

### Actual behavior
The internal smt.verify and smt.proof is used for both in memory and state db, but bridge between js and rust is not working.

### Steps to reproduce
```
describe('proof', () => {
            it('should generate proof and verify the result', async () => {
                const queries = [getRandomBytes(38), getRandomBytes(38)];
                const proof = await db.proof(root, queries);

                const result = await db.verify(root, queries, proof);

                expect(result).toEqual(false);
            });
        });
```
above unit test should pass in the state_db.spec.js

### PR DESCRIPTION
**Pull request by matjazv**
### What was the problem?

This PR resolves #65

### How was it solved?

- Fixed a bug in `smt.rs` module (`calc_query_proof_from_result` function)
- Fixed a bug in `state_db.rs` module (`prove` and `js_verify` functions)
- Fixed a bug where some JS unit tests randomly fail

### How was it tested?

- Some new JS unit tests were implemented
- All tests passed.

### CODE REVIEW

File: src/smt.rs [hunk 1]
```diff
@@ -1237,7 +1237,8 @@ impl SparseMerkleTree {
             ancestor_hashes.push_back(d.current_node.hash.value_as_vec());
             let pair = Arc::new(KVPair::new(
                 &d.current_node.key,
-                &d.current_node.hash.key()[PREFIX_LEAF_HASH.len() + HASH_SIZE..],
+                &d.current_node.hash.key()
+                    [PREFIX_LEAF_HASH.len() + usize::from(self.key_length)..],
```
Comment (hrmhatef) [inline src/smt.rs:1241]: KeyLength has From trait for `usize` so, it would be better to use `self.key_length.into()`

**Review by hrmhatef — CHANGES_REQUESTED** [review]
Thank you for fixed some bugs.

I just have a minor change request.

**Review by hrmhatef — APPROVED** [review]
